# Generated by Django 5.1.6 on 2025-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
