# Generated by Django 5.1.6 on 2025-06-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.country'),
        ),
    ]
