# Generated by Django 5.1.6 on 2025-06-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_newsletteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremail',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
