# Generated by Django 6.0 on 2026-09-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='physical_sim_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_sim_store_setting', to='store.category'),
        ),
    ]
