# Generated by Django 6.0 on 2026-09-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storesettings_physical_sim_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='physical_sim_category',
        ),
    ]
