# Generated by Django 6.0 on 2026-09-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_storesettings_physical_sim_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='internet_tools_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_tools_store_setting', to='store.category'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='physical_sim_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_sim_store_setting', to='store.category'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='privacy_tools_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_tools_store_setting', to='store.category'),
        ),
    ]
