# Generated by Django 5.1.6 on 2025-06-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
