# Generated by Django 5.1.6 on 2025-06-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='tech', max_length=100),
            preserve_default=False,
        ),
    ]
