# Generated by Django 6.0 on 2026-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_nowpayments_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fez_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fez_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
