# Generated by Django 6.0 on 2026-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_fez_order_id_order_fez_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fez_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
