# Generated by Django 6.0 on 2026-10-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fez_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fez_tracking_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
