# Generated by Django 5.1.6 on 2025-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='consultation',
            name='subject',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
