# Generated by Django 5.1.6 on 2025-06-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_rename_submitted_at_consultation_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
